ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
        BucketName: ${self:custom.s3ImagesBucket}
        PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
        CorsConfiguration:
            CorsRules:
                - AllowedOrigins:
                      - ${env:CLIENT_URL}
                  AllowedMethods:
                      - GET
                      - PUT
                      - POST
                      - DELETE
                  AllowedHeaders:
                      - '*'
                  ExposedHeaders:
                      - ETag
                  MaxAge: 3000
ImagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: Rekosearch-ImagesTable
        AttributeDefinitions:
            - AttributeName: imageId
              AttributeType: S
            - AttributeName: uploadedAt
              AttributeType: N
            - AttributeName: userId
              AttributeType: S
        KeySchema: # allows image search for last uploaded
            - AttributeName: imageId
              KeyType: HASH
            - AttributeName: uploadedAt
              KeyType: RANGE
        GlobalSecondaryIndexes:
            - IndexName: userId-imageId-index # allows image search by user
              KeySchema:
                  - AttributeName: userId
                    KeyType: HASH
                  - AttributeName: imageId
                    KeyType: RANGE
              Projection:
                  ProjectionType: ALL
              ProvisionedThroughput:
                  ReadCapacityUnits: 1
                  WriteCapacityUnits: 1
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        TimeToLiveSpecification:
            AttributeName: ttl # UNIX timestamp
            Enabled: true
LabelsTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: Rekosearch-LabelsTable # allows image search by label
        AttributeDefinitions:
            - AttributeName: label
              AttributeType: S
            - AttributeName: imageId
              AttributeType: S
        KeySchema:
            - AttributeName: label
              KeyType: HASH
            - AttributeName: imageId
              KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
RekognitionCollection:
    Type: AWS::Rekognition::Collection # allows image search by similar
    Properties:
        CollectionId: ${self:custom.rekognitionCollectionId}
