service: Rekosearch-serverless
frameworkVersion: '4'

provider:
    name: aws
    runtime: nodejs20.x
    region: us-west-1
    httpApi:
        cors:
            allowedOrigins:
                - ${env:CLIENT_URL}
            allowCredentials: true
        authorizers:
            jwtCognitoAuthorizer:
                type: jwt
                identitySource: $request.header.Authorization
                issuerUrl:
                    Fn::Sub: 'https://cognito-idp.${aws:region}.amazonaws.com/${env:COGNITO_USER_POOL}'
                audience: ${env:COGNITO_USER_POOL_CLIENT}
    environment:
        SERVERLESS_AWS_REGION:
            Ref: AWS::Region
        CLIENT_URL: ${env:CLIENT_URL}
        IMAGES_BUCKET_NAME: ${self:custom.s3ImagesBucket}
        REKOGNITION_COLLECTION_ID: ${self:custom.rekognitionCollectionId}
        IMAGES_TABLE_NAME:
            Ref: ImagesTable
        LABELS_TABLE_NAME:
            Ref: LabelsTable

package:
    individually: true
    patterns:
        - '!node_modules/*'

functions: ${file(./serverless-functions.yml)}

resources:
    Resources: ${file(./serverless-resources.yml)}

plugins:
    - serverless-iam-roles-per-function

custom:
    s3ImagesBucket: rekosearch-images-${sls:stage}
    rekognitionCollectionId: rekosearch-images-collection-${sls:stage}
