ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
        BucketName: ${self:custom.s3ImagesBucket}
        PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
        CorsConfiguration:
            CorsRules:
                - AllowedOrigins:
                      - ${env:CLIENT_URL}
                  AllowedMethods:
                      - GET
                      - PUT
                      - POST
                      - DELETE
                  AllowedHeaders:
                      - '*'
                  ExposedHeaders:
                      - ETag
                  MaxAge: 3000
ImagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: Rekosearch-ImagesTable
        AttributeDefinitions:
            - AttributeName: imageId
              AttributeType: S
            - AttributeName: uploadedAt
              AttributeType: N
            - AttributeName: userId
              AttributeType: S
            - AttributeName: category
              AttributeType: S
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        TimeToLiveSpecification:
            AttributeName: ttl # UNIX timestamp
            Enabled: true
        KeySchema:
            - AttributeName: imageId # Primary Key (unique identifier)
              KeyType: HASH
        GlobalSecondaryIndexes:
            - IndexName: userId-imageId-index # Fetch user's recent images
              KeySchema:
                  - AttributeName: userId
                    KeyType: HASH
                  - AttributeName: imageId
                    KeyType: RANGE
              Projection:
                  ProjectionType: ALL
              ProvisionedThroughput:
                  ReadCapacityUnits: 1
                  WriteCapacityUnits: 1
            - IndexName: category-uploadedAt-index # General image browsing
              KeySchema:
                  - AttributeName: category
                    KeyType: HASH
                  - AttributeName: uploadedAt
                    KeyType: RANGE
              Projection:
                  ProjectionType: ALL
              ProvisionedThroughput:
                  ReadCapacityUnits: 1
                  WriteCapacityUnits: 1
LabelsTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: Rekosearch-LabelsTable # allows image search by label
        AttributeDefinitions:
            - AttributeName: label
              AttributeType: S
            - AttributeName: imageId
              AttributeType: S
        KeySchema:
            - AttributeName: label
              KeyType: HASH
            - AttributeName: imageId
              KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: Rekosearch-UsersTable # users' metadata
        AttributeDefinitions:
            - AttributeName: userId
              AttributeType: S
        KeySchema:
            - AttributeName: userId
              KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
RekognitionCollection:
    Type: AWS::Rekognition::Collection # allows image search by similar
    Properties:
        CollectionId: ${self:custom.rekognitionCollectionId}
