service: QuillStream-serverless
frameworkVersion: '4'

provider:
    name: aws
    runtime: nodejs20.x
    region: us-west-1
    httpApi:
        cors:
            allowedOrigins:
                - ${env:CLIENT_URL}
            allowCredentials: true
    environment:
        SERVERLESS_AWS_REGION:
            Ref: AWS::Region
        CLIENT_URL: ${env:CLIENT_URL}
        IMAGES_BUCKET_NAME: ${self:custom.s3ImagesBucket}
        REKOGNITION_COLLECTION_ID: ${self:custom.rekognitionCollectionId}

package:
    individually: true
    patterns:
        - '!node_modules/*'

functions: ${file(./serverless-functions.yml)}

resources:
    Resources: ${file(./serverless-resources.yml)}

plugins:
    - serverless-iam-roles-per-function

custom:
    dynamodbTableUrl: "arn:aws:dynamodb:${opt:region, self:provider.region}:${aws:accountId, '*'}:table"
    s3ImagesBucket: rekosearch-images-${sls:stage}
    rekognitionCollectionId: rekosearch-images-collection-${sls:stage}
